### ISSUE TITLE
API key invalid - bittrex

### ISSUE THREAD

**Issue by dimoimo** [askmike/gekko#1054]
keep getting 

2017-08-29 21:42:47 (DEBUG):    getTicker result { Bid: 0.02630017, Ask: 0.02677724, Last: 0.02630004 }
2017-08-29 21:42:47 (DEBUG):    getPortfolio called
2017-08-29 21:42:47 (ERROR):    getPortfolio Error { success: false, message: 'APIKEY_INVALID', result: null }
2017-08-29 21:42:47 (DEBUG):    Bittrex returned an error, retrying. [ [Function] ]
2017-08-29 21:42:57 (DEBUG):    getPortfolio called
2017-08-29 21:42:58 (ERROR):    getPortfolio Error { success: false, message: 'APIKEY_INVALID', result: null }
2017-08-29 21:42:58 (DEBUG):    Bittrex returned an error, retrying. [ [Function: bound] ]

each time I run. I checked for all misplaced commas, etc. 

here is the key section of my config file:

 config.trader = {
  enabled: true,
  key: '*******************************************',
  secret: '**********************************************',
  username: '', // your username, only required for specific exchanges.
  passphrase: '', // GDAX, requires a passphrase.
}

I've tried with several keys, and redownloading. Not sure what to do here

**Comment by askmike** [comment]
Have you filled in both the key and the secret? Are you sure the API key is valid for viewing balance and trading? Is the API key limited to an IP?

**Comment by dimoimo** [comment]
Yes I've got both completed, the API key has all permissions except withdrawal (not sure if that makes the difference?) 

my next bet is to try a different exchange

**Comment by askmike** [comment]
I will test soon, but ping @imperator6

**Comment by imperator6** [comment]
@dimoimo It works in my local pc, but i've not checked out the merged develop branch. Could try to start gekko in UI mode and add the keys via the gui. Afterwards it should also work in console mode.

**Comment by anthonyjbarnes** [comment]
I have been looking froward to using gekko on bittrex but have the same issue. I get the error when gekko runs getPortfolio

**Comment by markanderson** [comment]
For anyone still experiencing this problem, a hacky work-around in the meantime is to edit the bittrex exchange file directly and set the key and secret. That will get you up and running until a better solution is merged in.

**Comment by krieghof** [comment]
@markanderson Thanks this workaround also worked for me. We should find a fix for this.

**Comment by askmike** [comment]
This should be fixed in develop now. @dimoimo @markanderson can you try that branch? You can download it here: https://github.com/askmike/gekko/tree/develop

**Comment by ghost** [comment]
Still not working :( Used hack with editing bittrex.js.

**Comment by carlosatta** [comment]
Still not working...

> data:    gekko.js:25419 - 2018-01-28 18:21:25 (DEBUG):	getPortfolio called
data:    gekko.js:25419 - 2018-01-28 18:21:25 (ERROR):	getPortfolio Error { success: false, message: 'APIKEY_INVALID', result: null }
data:    gekko.js:25419 - 2018-01-28 18:21:25 (DEBUG):	Bittrex returned an error, retrying. [ [Function: bound] ]

**Comment by ghost** [comment]
Im having the same issue
Tried:
Adding the API from the Web ui.
Manually adding it in the bittrex.js  exchange file
Creating a new key on bittrex and testing it, It works

![image](https://user-images.githubusercontent.com/36680933/37181093-ae681e48-237f-11e8-8a08-ffa8749ea29d.png)

**Comment by askmike** [comment]
Bittrex live trading is disabled in Gekko 0.6 because of this bug, see #2310 for more details.

**Comment by melroy89** [comment]
wont fix?

I think its handy to fix this issue right?
https://gekko.wizb.it/docs/introduction/supported_exchanges.html
