### ISSUE TITLE
Binance live trader not working

### ISSUE THREAD

**Issue by TonyXu09** [askmike/gekko#1667]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Ran binance live trader from both UI and command line

* **Expected result** (what you hoped would happen)
should have executed trades

* **Actual result** (unexpected outcome)
When running from the UI, it doesn't give any errors but it does not trade. I get the loading indicator in the runtime area when clicking in to the live trader.
If running from the command line, I get this error

`2018-01-11 02:12:18 (DEBUG):    [binance.js] entering "getTicker" callback after api call, err: Error: Response code 404
    at Request.e [as _callback] (/mnt/d/Projects/gekko/node_modules/binance/lib/rest.js:66:37)
    at Request.self.callback (/mnt/d/Projects/gekko/node_modules/binance/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/mnt/d/Projects/gekko/node_modules/binance/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/mnt/d/Projects/gekko/node_modules/binance/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)  data: <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no,email=no,address=no">
    <title>Binance</title>
    <link rel="Shortcut Icon" href="favicon.ico">
</head>
<style>
    body{margin: 0}
    .img{width: 611px;margin: 68px auto 0}
    .info{width: 370px;margin: 0 auto ;text-align: center;}
    .info h3{margin: 0;font-size: 25px;color: #333;font-weight: normal;}
    .info p{font-size: 14px;font-family: Arial;color: #333;line-height: 18px;margin: 0}
</style>
<body>
<div class="img"><img alt="" src="404.jpg"></div>
<div class="info">
    <h3>出错啦！您访问的网页不存在。</h3>
    <p>Sorry! The page you’re looking for cannot be found.</p>
</div>
</body>
</html>
2018-01-11 02:12:18 (ERROR):    [binance.js] unable to get ticker {}`

here is my config

`config.watch = {

  // see https://gekko.wizb.it/docs/introduction/supported_exchanges.html
  exchange: 'binance',
  currency: 'BTC',
  asset: 'FUN',

  // You can set your own tickrate (refresh rate).
  // If you don't set it, the defaults are 2 sec for
  // okcoin and 20 sec for all other exchanges.
  // tickrate: 20
}

config.tradingAdvisor = {
  enabled: true,
  method: 'custom',
  candleSize: 1, // in minutes
  historySize: 3,
  adapter: 'sqlite'
}

config.paperTrader = {
  enabled: true,
  // report the profit in the currency or the asset?
  reportInCurrency: true,
  // start balance, on what the current balance is compared with
  simulationBalance: {
    // these are in the unit types configured in the watcher.
    asset: 1,
    currency: 100,
  },
  // how much fee in % does each trade cost?
  feeMaker: 0.1,
  feeTaker: 0.1,
  feeUsing: 'maker',
  // how much slippage/spread should Gekko assume per trade?
  slippage: 0.05,
}

  enabled: true,
  key: 'KEYHERE',
  secret: 'SECRET HERE',
  username: '', // your username, only required for specific exchanges.
  passphrase: '' // GDAX, requires a passphrase.

config['I understand that Gekko only automates MY OWN trading strategies'] = true;
`

**Comment by davidlimap** [comment]
From what I saw in the rest.js file of the binance module the url base would be https://api.binance.com/api/v1/ instead of https://www.binance.com/api/v1/ (see in https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)

**Comment by joaosauer** [comment]
The binance package used in the stable/develop branch is too old(1.0.2). We would need a merge from the PR 1550 to allow us to use the binance 1.2.1 package. This would probably fix the issue above

**Comment by nakaori** [comment]
I tried replacing the API base url and get the same result. The api is reachable via  https://www.binance.com/api/v1/  also.

**Comment by davidlimap** [comment]
I updated the binance module, but it does not work too.

**Comment by nakaori** [comment]
it's working for me. remember to npm install again after pulling from git!

**Comment by cmroche** [comment]
This is due to a module update changing the way URLs were constructed in Binance, fixed in the latest stable release with the latest binance module

`npm uninstall binance` (or was that remove?)
`npm install binance`

**Comment by joaosauer** [comment]
I'm also getting an error, and I followed all the steps said here: (npm uninstall, install, install everything)
I'm still getting the error 400:
```
$ npm uninstall binance
removed 4 packages in 2.554s
$ npm install binance
+ binance@1.2.2
added 4 packages in 3.528s
$ npm install
up to date in 2.551s
$ node web/server.js 
Serving Gekko UI on http://localhost:3000/

  <-- GET /api/imports
  --> GET /api/imports 200 5ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 11b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 1,419ms 81.12kb
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 0ms 11b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 3ms 81.12kb
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 11b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 4ms 81.12kb
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/performanceAnalyzer 200 4ms 144b
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 130b
  --> GET /api/strategies 200 7ms 2.03kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/performanceAnalyzer 200 1ms 144b
  --> GET /api/configPart/candleWriter 200 1ms 47b
  <-- GET /api/strategies
  --> GET /api/strategies 200 4ms 2.03kb
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 130b
  <-- POST /api/startGekko
Gekko 606405431856857 started
  --> POST /api/startGekko 200 20ms 147b
  <-- POST /api/startGekko
Gekko 280214208814175 started
  --> POST /api/startGekko 200 5ms 370b
RECEIVED ERROR IN GEKKO 280214208814175


Gekko encountered an error and can't continue


Gekko encountered an error and can't continue

Error:

[binance.js] Response code 400

Meta debug info:

Gekko version: v0.5.12
Nodejs version: v8.5.0
```

**Comment by joaosauer** [comment]
Good news
In my case, the error 400 was because my computer was 2 secs wrong with an atomic time server.
I use mac and after update the time, it's now working for me. (No trader yet, but I will keep you updated)

Cheers,
Joao

**Comment by askmike** [comment]
@joaosauer great, let us know!

**Comment by Kralg** [comment]
I am also getting error 400 and I downloaded gekko yesterday. I am running it on ubuntu. Does anyone have a solution for this? 
Gekko encountered an error and can't continue

```
Error:

[binance.js] Response code 400

Meta debug info:

Gekko version: v0.5.14
Nodejs version: v9.9.0

```

**Comment by cmroche** [comment]
@Kralg And you verified that it isn’t your system clock being off by too much?

**Comment by Kralg** [comment]
@cmroche  I checked time with time.is. It is synchronized. I am using Ubuntu 16.04 and ntp for time synchronization. @joaosauer mentioned atomic time. I can see that in this case TAI seconds are different from UTC. Do I have to synchronize with TAI? If so, can you advice on how to do that?

**Comment by cmroche** [comment]
@Kralg I am not familiar enough with your environment to really state what the problem is, but generally speaking this was the cause of the error you are seeing.

However I think with the latest release 0.5.14 a time sync function should be present in the binance setup to automatically handle this now. Update to latest, run `npm update` to update modules, and then try again?

If that all fails, then please look into adding some debug information in the code the determine what the precise error coming back from Binance is and reporting back with that info.

**Comment by Kralg** [comment]
@cmroche well I think you mean Gekko version, but I have the 0.5.14, this is written in my previous message, I think. Or do you think that even 0.5.14 was changed without the version number increase?

**Comment by cmroche** [comment]
@Kralg It looks like @askmike pushed a changed recently to give more information on the error, it's in the develop branch commit f06c3d277428decac3217744a04841f73769d6bd
