### ISSUE TITLE
Binance: Rountrip entry and exit dates are broken

### ISSUE THREAD

**Issue by mronus** [askmike/gekko#1687]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started live trade

* **Expected result** (what you hoped would happen)
I was expecting to see the correct entry and exit dates in the roundtrips table

* **Actual result** (unexpected outcome)
All dates are corrupted in the roundtrips table as seems in the following ss:
![34905663-b0f2258c-f86e-11e7-98c8-967516c4b986](https://user-images.githubusercontent.com/2014677/34916562-4a8a33d8-f94b-11e7-9eb9-9b3eeb7a4a04.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
There is a similar issue reported for poloniex: #942

**Comment by cmroche** [comment]
All timestamps coming from binance or unix time, so either it isn't Binance specific or this is possibly already fixed (I recall seeing a timestamp fix for something over the last two weeks).

Could you check it on the develop branch and confirm please. If you are backtesting, it is possible that the timestamps in your history data are wrong from a previous bug, please delete the DB files in the history folder and re-import.

Let me know if that works.

**Comment by joaosauer** [comment]
It was fixed.
I was having the same issue and what I need is to make a new git clone, then, checkout develop and npm install. This then was fixed.

**Comment by rkingy** [comment]
I'm running the latest dev code (downloaded today) and also still seeing this issue using live trading bot on binance... BTCXLM

![screenshot 2018-01-29 17 39 43](https://user-images.githubusercontent.com/15899802/35493886-7338ba12-051b-11e8-84e4-6e445ec79c54.jpg)

**Comment by cmroche** [comment]
@rkingy Assuming you are back testing, did you delete and re-import market data? You probably have bad timestamps stored in the database.

**Comment by Pascal66** [comment]
[deleted by @askmike]

**Comment by cmroche** [comment]
@Pascal66 You likely have a virus in your computer, spamming your address book. 

@askmike Can you delete the message? I don't want to report the user as a spammer, since it was probably unintentional.

**Comment by cmroche** [comment]
@Pascal66 Did you respond to the wrong email by accident, or perhaps you have a virus on your computer spamming your contact list?

**Comment by rkingy** [comment]
@cmroche No actually it is fine when I am backtesting. The issue only occurs when using live tradebot mode. I'm not sure about Paper trading.

I looked at the code, and seems there are slight difference to the getOrder function compared to say bitfinex market.. I wondered if maybe the date.time is slightly different format? But am pretty new to looking at this code.. so no idea really..
 var date = moment.unix(data.time);

**Comment by cmroche** [comment]
@rkingy Yeah, that would be wrong. Binance uses milliseconds, unix() expects seconds epoch time. However my code shows we are using this right now `date: moment(trade.timestamp).unix()`, which is correct. As I recall this was a bug someone fixed shortly after Christmas.

If you switch to the develop branch it'll probably work for you then.

**Comment by rkingy** [comment]
@cmroche I've fixed this on my local. 

I'm not sure how to contribute code to this project.. but here is what I added.

```
    //Data.time is a 13 digit milliseconds unix time stamp.
    //https://momentjs.com/docs/#/parsing/unix-timestamp-milliseconds/ 
    var date = moment(data.time);
```

**Comment by Platiz0** [comment]
its on kraken too...but yet it shows 10 trades instead of just one because it cancelled a bunch before the trade got covered (im guessing) but the 48years is there https://i.imgur.com/JnpoSwE.png

**Comment by rkingy** [comment]
@askmike I've got a fix for this that is currently working on my live trades.. how do I contribute this? Pushing up on Dev branch gives me access denied so I assume there's a process to follow

**Comment by GuybrushX** [comment]
@rkingy 
I'm pretty new to GitHub but I think you create a fork/copy/clone of the project and than a PR (Pull Request) so one of the developers with commit rights can check and merge your changes.

Pull Request because you ask the developers to pull your changes, check them, accept/deny them.

Perhaps you can create a PR with a local file, too but you need to check or google|bing that yourself.

**Comment by askmike** [comment]
fixed in #1846!
