### ISSUE TITLE
Cannot run Gekko

### ISSUE THREAD

**Issue by ChadTaljaardt** [askmike/gekko#2150]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
```
 node gekko --ui
```

**Expected result** (what you hoped would happen)
Gekko to run

**Actual result** (unexpected outcome)
```
 gekko git:(stable) ✗ node gekko --ui


    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.14
        I'm gonna make you rich, Bud Fox.


/Users/chadtaljaardt/Desktop/tradingbot/gekko/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];

TypeError: Cannot read property '1' of null
    at module.exports (/Users/chadtaljaardt/Desktop/tradingbot/gekko/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/chadtaljaardt/Desktop/tradingbot/gekko/node_modules/promisify-node/index.js:61:29)
    at module.exports (/Users/chadtaljaardt/Desktop/tradingbot/gekko/node_modules/promisify-node/index.js:164:10)
    at Object.<anonymous> (/Users/chadtaljaardt/Desktop/tradingbot/gekko/web/routes/scanDateRange.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/chadtaljaardt/Desktop/tradingbot/gekko/web/server.js:56:26)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)

```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
➜  gekko git:(stable) ✗ npm --version
6.0.0
➜  gekko git:(stable) ✗ node --version
v10.0.0
```

**Comment by Ishan2607** [comment]
______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.5.14
	I'm gonna make you rich, Bud Fox. 


/Users/ishanbanerjee/Downloads/gekko-develop/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
    at module.exports (/Users/ishanbanerjee/Downloads/gekko-develop/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/ishanbanerjee/Downloads/gekko-develop/node_modules/promisify-node/index.js:61:29)
    at module.exports (/Users/ishanbanerjee/Downloads/gekko-develop/node_modules/promisify-node/index.js:164:10)
    at Object.<anonymous> (/Users/ishanbanerjee/Downloads/gekko-develop/web/routes/scanDateRange.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ishanbanerjee/Downloads/gekko-develop/web/server.js:56:26)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
Ishans-iMac:gekko-develop ishanbanerjee$

**Comment by rbmarliere** [comment]
Hi. I was having the same problem and was able to fix it by applying this patch to node_modules/promisify-node/utils/args.js : 

<   var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
---
>   var args = func.toString().match(/function\s?.*?\(([^)]*)\)/)[1];

You just need to add that extra "?" character after \s .

Cheers.

**Comment by clementpl** [comment]
Hello,
I got the same problem during my installation.
I upgrade promisify-node in package.json
    "promisify-node": "^0.5.0",

I got a problem with sqlite3 as well, i upgrade it in package.json:
    "sqlite3": "^4.0.0",

rm -rf node_modules
npm i

And all seems to work.

**Comment by askmike** [comment]
Can you try again? I released a major new version recently (0.6) which I think also fixed this issue. Assuming this is now fixed, if not please comment :)

**Comment by hilkoc** [comment]
It's not fixed. I've got the same problem on v0.6.2 and latest develop.

EDIT:  after following @clementpl s suggestion,  upgrade promisify-node in package.json
"promisify-node": "^0.5.0",
it seems to work.
