### ISSUE TITLE
Trailing SL, double SELL advice

### ISSUE THREAD

**Issue by mark-sch** [askmike/gekko#2488]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Backtest on CLI new SL feature

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)
I am tweaking my strategy to take advantage of the new traiing SL feature. I did a lot of debugging, new advices with SL are recognized well but each onStopTrigger inside the PaperTrader will fire two SELL advices. For that reason roundtrips are probably shown twice in the result.
What I found useful/necessary inside the strategy is the trigger information inside the trade event(object), so the strategy can use this info - I added this.
Inside paper trader, onStopTrigger method, the event deferredEmit('tradeCompleted') is emitted (so it needs all the portofolio and position calculating code previously, which is already inside processAdvice). Did you prevent the advice event for a particular reason?
I tested with this.deferredEmit('advice') and get same excution behaviour but plugins like emailer are able to participate from the advice event. After fixing the double SELL advice I could suggest a PR, found and fixed some typos also.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) REPORT:
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) entry date (UTC)  	exit date (UTC)  	exposed duration	P&L 	profit
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) 2018-08-09 07:33	2018-08-09 13:12	6 hours         	-15.05	-1.51
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) 2018-08-09 07:33	2018-08-09 13:12	6 hours         	-15.05	-1.51
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) 2018-08-14 02:09	2018-08-14 03:06	an hour         	-10.25	-1.04
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) 2018-08-14 02:09	2018-08-14 03:06	an hour         	-10.25	-1.04
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) 2018-08-19 03:37	2018-08-19 17:47	14 hours        	4.41	0.45
2018-08-29 12:15:12 (INFO):	(ROUNDTRIP) 2018-08-19 03:37	2018-08-19 17:47	14 hours        	4.41	0.45

2018-08-29 12:15:10 (DEBUG):	Check database exists: binance
2018-08-29 12:15:10 (DEBUG):	Database exists: binance
2018-08-29 12:15:10 (DEBUG):	Postgres connection pool is ready, db binance
2018-08-29 12:15:10 (DEBUG):	 ***** buy after low peak ***** 1533799920000
########## processAdvice, TRIGGER: {"type":"trailingStop","trailPercentage":1.8,"trailValue":114.26976}
2018-08-29 12:15:10 (INFO):	2018-08-09 09:33:00: Paper trader simulated a BUY @ 6304.83 USDT 		0.00000000 USDT	=> 0.15837064 BTC
!!!!!!!!!!!!!!!!!!!!!!! onStopTrigger
########## processAdvice, TRIGGER: {"type":"trailingStop","id":"advice-1","ohhh":"no"}
2018-08-29 12:15:10 (DEBUG):	{"id":"trade-2","adviceId":"trade-1","action":"sell","cost":1.4773842708359468,"amount":0.15813308403949122,"price":6219.1,"portfolio":{"asset":0,"currency":983.44546295},"balance":983.44546295,"date":"2018-08-09T13:12:00.000Z","effectivePrice":6209.771350000001,"feePercent":0.15,"status":"tradeCompleted","origin":"trailingStop"}
2018-08-29 12:15:10 (INFO):	2018-08-09 15:12:00: Paper trader simulated a SELL @ 6219.10 USDT 	983.44546295 USDT <= 0.00000000 BTC
########## processAdvice, TRIGGER: undefined
2018-08-29 12:15:10 (DEBUG):	{"id":"trade-3","adviceId":"advice-2","action":"sell","cost":0,"amount":0.15813308403949122,"price":6219.1,"portfolio":{"asset":0,"currency":983.44546295},"balance":983.44546295,"date":"2018-08-09T13:12:00.000Z","effectivePrice":6209.771350000001,"feePercent":0.15,"status":"tradeCompleted","origin":"advice"}
2018-08-29 12:15:10 (INFO):	2018-08-09 15:12:00: Paper trader simulated a SELL @ 6219.10 USDT 	983.44546295 USDT <= 0.00000000 BTC

**Comment by askmike** [comment]
> I did a lot of debugging, new advices with SL are recognized well but each onStopTrigger inside the PaperTrader will fire two SELL advices.

Very strange, it shouldn't do this and doesn't do this in my tests.

> Did you prevent the advice event for a particular reason?

I'm not 100% sure if I am following your report, but might be as follows:

----

Just to rule something out: there was a bug until yesterday (fixed in develop 1 hour before you opened this ticket, in this commit: c5f4f81977447226eab020b213516d5e959e5b07) that caused the following behavior:

- If you trigger a long with a trailingStop gekko will do a buy & create the trailing stop
- if the trailing stop triggers gekko would do a sell - however gekko's strategy code would ignore this sell. So from that perspective the last thing that happened is a buy (and this code only allows you to buy after a sell, and sell after a buy).
- if your strategy now fires a sell (even though the last action was a sell from the trailingStop) Gekko would push that through, leading to the behavior you seen.

Would you be able to test the latest develop branch? And see if your issue is fixed? Thanks!

**Comment by mark-sch** [comment]
Hi Mike, your baseTradingMetod.js change looks promising, great. I just cherry-picked your last two commits...unfortunately it did not solve the double sell prob.
The current log is in this gist: https://gist.github.com/mark-sch/39f069b0281b940d6f4c63681684f562
Wierd thing is, there is only one relayAdvice for SELL but the processAdvice method from paperTrader is called twice. The possibility to give a short avdvice from strategy is completely commented out right now for testing.

**Comment by mark-sch** [comment]
Good news, your last commits did the trick. Code got temporarily messed up here during merge - trading adviser was subscribing twice. Will continue testing now...
