### ISSUE TITLE
Not fetching prepared data for warmup

### ISSUE THREAD

**Issue by GeorgeMurAlkh** [askmike/gekko#2598]
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to start Paper Trading with big warmup (1000 x 5m candles). Binance USDT/EOS pair. Fetched 7 previous days. Started paper trading and getting wrong info from bot.

**Expected result** (what you hoped would happen)
Local data combined with fetched from exchange data, and fed to the strategy.

**Actual result** (unexpected outcome)
Local data not loaded and combined with fetched. Fetched data not meeting requirements from configuration (too little data)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
2018-10-17 04:24:51 (INFO):	Setting up:
2018-10-17 04:24:51 (INFO):		 Candle writer
2018-10-17 04:24:51 (INFO):		 Store candles in a database
2018-10-17 04:24:51 (INFO):	

2018-10-17 04:24:51 (INFO):	Setting up:
2018-10-17 04:24:51 (INFO):		 Trading Advisor
2018-10-17 04:24:51 (INFO):		 Calculate trading advice
2018-10-17 04:24:51 (INFO):		 Using the strategy: neuralnet_zschro
2018-10-17 04:24:52 (ERROR):	Failed to load indicator Alligator
2018-10-17 04:24:52 (ERROR):	Failed to load indicator HEIKEN
2018-10-17 04:24:52 (ERROR):	Failed to load indicator PIVOTHIGHLOW
2018-10-17 04:24:52 (ERROR):	Failed to load indicator RSI-beta
2018-10-17 04:24:52 (INFO):		The trading method requests 5000 minutes of historic data. Checking availablity..
2018-10-17 04:24:52 (INFO):	

2018-10-17 04:24:52 (INFO):		Local data is still too recent, trying to get as much as possible from the exchange
2018-10-17 04:24:52 (INFO):		Preventing Gekko from requesting 5000 minutes of history.
2018-10-17 04:24:52 (DEBUG):		Fetching exchange data since 240 minutes ago
2018-10-17 04:24:53 (DEBUG):		Available exchange data:
2018-10-17 04:24:53 (DEBUG):			from: 240 minutes ago
2018-10-17 04:24:53 (DEBUG):			to: 181 minutes ago
2018-10-17 04:24:53 (DEBUG):		Exchange offered more data than locally available. Ignoring local data
2018-10-17 04:24:53 (DEBUG):		Unable to stitch datasets.
2018-10-17 04:24:53 (INFO):		Not seeding locally available data to the trading method.
2018-10-17 04:24:53 (INFO):	Setting up:
2018-10-17 04:24:53 (INFO):		 Paper Trader
2018-10-17 04:24:53 (INFO):		 Paper trader that simulates fake trades.
2018-10-17 04:24:53 (INFO):	

2018-10-17 04:24:53 (INFO):	Setting up:
2018-10-17 04:24:53 (INFO):		 Performance Analyzer
2018-10-17 04:24:53 (INFO):		 Analyzes performances of trades
2018-10-17 04:24:53 (INFO):	

2018-10-17 04:24:53 (INFO):	Starting to watch the market: Binance EOS/USDT
2018-10-17 04:24:53 (DEBUG):	scheduling ticks
2018-10-17 04:24:53 (DEBUG):	Requested EOS/USDT trade data from Binance ...
2018-10-17 04:24:53 (DEBUG):	Processing 500 new trades. From 2018-10-17 00:57:20 UTC to 2018-10-17 01:24:50 UTC. (28 minutes)
```
Is the problem Binance? 
Is it possible to use previously collected data in UI mode?

**Comment by hiyan** [comment]
This usually means your latest local history is older than what the exchanges currently have (240 minutes in your case) creating a gap. Re-run the importer and it should be fixed.

I have a simple checker here (https://github.com/hiyan/gekkowk/blob/develop/plugins/sqlite/gapCheck.js).

You may need to run it a few times to ensure no gaps in your db.

**Comment by askmike** [comment]
> 2018-10-17 04:24:52 (INFO):		Local data is still too recent, trying to get as much as possible from the exchange

It found local data, but not older than `240 minutes ago` (in the latest "data window" that is).

If you import make sure you import until *right now*: if you have 1 year of data until 24 hours ago Gekko won't be able to use it as it doesn't know what happened between now and the last 24 hours. Also note that the importer is set to UTC, if you are in a different timezone make sure you take this into account.

---

If this all doesn't fix it please comment here and we can reopen.

**Comment by ripley** [comment]
Seems this issue is still there. I tried to import history several times (till NOW) but always get the error ...

2018-12-17 21:04:32 (DEBUG):            Unable to stitch datasets.
2018-12-17 21:04:32 (INFO):             Not seeding locally available data to the trading method.
2018-12-17 21:04:32 (INFO):             The exchange does not return enough data. 0 minutes are still missing.

I read the code and find a condition in dataStitcher.js:
      var stitchable = localData && exchangeData.from <= localData.to;
...
      } else if(!stitchable) {
        log.debug('\tUnable to stitch datasets.')
...

I added some log and dumped these three variables:  localData, exchangeData.from and localData.to.
the log's output is as:
2018-12-17 21:04:32 (DEBUG):            Stichable status:
2018-12-17 21:04:32 (DEBUG):                    localData: { from: 1544787840, to: 1545051720 }
2018-12-17 21:04:32 (DEBUG):                    exchangeData.from: moment.utc("2018-12-17T13:02:44.000+00:00")
2018-12-17 21:04:32 (DEBUG):                    localDatato: moment.utc("2018-12-17T13:02:00.000+00:00")

I'm probably wrong but it's looks like the historical data can never be picked up, if I import history data from 

2018-12-14 13:00:00 to 2018-12-17 13:00:00 (now), 

and the import finished at  2018-12-17 13:02:00, then when user starts gekko the exchangeData.from should be around 13:02:00, and the exchangeData.from <= localData.to condition will always be false, in that case how could the historical data be picked up?
