### ISSUE TITLE
No Backtesting/importing Data possible in UI

### ISSUE THREAD

**Issue by Schlitten** [askmike/gekko#629]
After I figured out how to use the stable version and was quite smooth with backtesting I tried to get the ui working.
1.) downloaded the develop zip
2.) installed dependencies (npm)
3.) started ui

So far everything worked fine.

Problem # 1 importing data doesn't work. I can start the import and it also takes time until it finished importing. After the import is finished (successful according to Web ui) no data can be found and no history folder was created.

Problem # 2 if I start backtesting (imported history data from stable version) I get the graph but no buy and sell indicators and results are also not calculated:
![screen shot 2017-03-17 at 16 01 32](https://cloud.githubusercontent.com/assets/26486861/24049034/1333f310-0b2b-11e7-82d5-90f9023d8bdb.png)

the console delivers also strange output (several times number 2, happens only with CCI Strategy):
![screen shot 2017-03-17 at 16 04 43](https://cloud.githubusercontent.com/assets/26486861/24049169/80fac004-0b2b-11e7-8541-8aba853a6774.png)

anything I missed out? latest MacOS

Thanks!

**Comment by thegamecat** [comment]
Oddly I am getting the NaN issue as well. On the debug-advice as well which seems odd.

**Comment by Zep18** [comment]
Hey, same here for problem 1, tried different exchanges, but dataset are invisible

Debian, with Gekko v0.4.4 and Gekko UI v0.1.2

**Comment by Schlitten** [comment]
@Zep18
does backtesting work for you?

**Comment by askmike** [comment]
My bad! Should be fixed now. Either git pull or redownload the zip.

**Comment by Schlitten** [comment]
thanks for fixing!

backtesting works great. Importer still not working (at least for me). Is the importer supposed to work?

**Comment by askmike** [comment]
It's supposed to work like [this](https://cloud.githubusercontent.com/assets/969743/24066517/444e78b8-0b6b-11e7-93df-2c578dc81c11.gif). If it is not, could you describe the problem in a new issue?

**Comment by thegamecat** [comment]
getting this error in console after a very short period of the backtester starting in ui:


  <-- POST /api/backtest
  xxx POST /api/backtest 500 7,778ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/freefall/gekkoinstalls/gekko-develop/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:103:7)



This is with any date range (changed or otherwise, any sized dataset and any strategy;rsi, talib macd and custom talib.

**Comment by askmike** [comment]
@thegamecat please open a new issue since this is not related to this one. EDIT: And when you do, please post extra data like: what exchange, what market, what settings (in the UI), etc.
