### ISSUE TITLE
invalid api key error

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#870]
error shows when i run gekko through the ui feature trader and on gdax
it says invalid api key and I generating it through the sandbox website
is there a way to fix this?

**Comment by thegamecat** [comment]
Create the file in root.

**Comment by askmike** [comment]
The ui feature is in progress and not stable. That branch is on github so other developers can work on the code and everyone can see progress. I would advise against running it and cannot offer any support for it.

**Comment by ghost** [comment]
@thegamecat ok, but in windows you need read write permission to create files in root, I looked into it and seems microsoft limited access to root so virus dont get into the OS.

**Comment by ghost** [comment]
@askmike ok, I just want to test it to provide feedback of any bugs or improvements that it could use

**Comment by askmike** [comment]
@ak9250 I just merged #737 into develop and fixed this bug.

Now you can test, and if you run into anything please create an issue :)

Note that there might be bugs and I cannot guarantee there won't be issues.

**Comment by ghost** [comment]
@askmike thanks I tried the develop branch and I still get the same error, note I am using the public.sandbox.gdax.com site and generate api key secret from there. Could that be the cause of the error?

![screenshot 168](https://user-images.githubusercontent.com/6818285/28503361-14c49d30-6fd3-11e7-9159-dd6e2482f51a.png)


I understand there will be bugs that is why I am using the developers sandbox to test things and make this better, thanks :)

**Comment by askmike** [comment]
@ak9250 can you provide a screenshot of copy some logs of the error? I thought you were talking about something else.

**Comment by ghost** [comment]
@askmike sorry screenshot attached now to previous post, let me know if you need anything else

**Comment by askmike** [comment]
So gekko normally connects to the real GDAX, not the sandbox. So you see this error because sandbox keys don't work on the real GDAX. Two things:

- gekko tries to buy and sell via limit orders, which only works if other people are trading. The GDAX sandbox is great but no one there is trading. I ran into the same issue when working on Gekko and if you want to use the sandbox you need to create a second GDAX sandbox account that can take orders created by the account connected to Gekko (you cannot take your own orders on single account).
- if you still want to use the sandbox, set [this to true](https://github.com/askmike/gekko/blob/develop/exchanges/gdax.js#L13).

**Comment by ghost** [comment]
@askmike ok thanks I will try this out, gdax really should improve their sandbox site for developers to test out on but until then I might just move to testing on the real site if this doesn't work out. 

thats another reason I like whaleclub because their demo and live platforms are identical and great for testing.
